---
name: Template repository

on: [push]

jobs:
  template:
    environment: terraform
    if: github.event.repository.name != 'kms-template-Basic'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: 'main'
    - name: Run replace.py
      run: |
        args=$(curl -s .github/configuration.json \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/KosikGroupTest/${{ github.event.repository.name }} | \
          jq '.description' | sed 's/\\\"/"/g' | sed 's/^.//;s/.$//'
        )
        echo $args
        python .github/replace.py --dir . --input $args
        rm .github/replace.py
        rm .github/workflows/template.yaml
    - name: Commit changes
      run: |
        git config --global user.email "noreply@github.com"
        git config --global user.name "github-actions"
        git add .
        git status
        git commit -am "Repository templated."
        git status
        git push
    - name: Delete description
      run: |
        curl -X PATCH -H "Authorization: token ${{ secrets.TF_GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/KosikGroupTest/${{ github.event.repository.name }} \
          -d '{"name": "${{ github.event.repository.name }}", "description": ""}'
